### ISSUE TITLE
Sommacoda

### ISSUE THREAD

**Issue by RuggieroB** [EnricoRuggieroB/ricorsione#2]
@FabioZTessitore  Sommacoda caricato a dicembre, noto che potrebbe esserLe sfuggito

**Comment by FabioZTessitore** [comment]
controllo

**Comment by FabioZTessitore** [comment]
prima di tutto bisogna aggiornare il gitignore e ripulire la cartella

**Comment by FabioZTessitore** [comment]
per il resto va bene, ma solo n2 deve essere positivo (perché?), n1 può anche essere negativo

**Comment by FabioZTessitore** [comment]
hai letto?

**Comment by RuggieroB** [comment]
Perché la funzione ricorsiva decrementa il secondo numero

**Comment by FabioZTessitore** [comment]
Perché la ricorso è consiste nel risolvere un problema di dello stesso tipo ma "più piccolo".
Il parziale aumenta di 1 e il secondo e numero diminuisce

**Comment by FabioZTessitore** [comment]
Ok

**Comment by RuggieroB** [comment]
Grazie 



Inviato da Libero Mail per iOS


domenica 22 marzo 2020, 18:24 +0100 da notifications@github.com  <notifications@github.com>:
